[project]
name = "agents-for-humans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "najani", email = "nikoajani7@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bedrock-agentcore>=1.22.0",
    "strands-agents>=1.53.0",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
agents-for-humans = "agents_for_humans:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
